<?php
/**
 * This template show bestseller product
 */
?>
<?php $_products = $this->myBest(); ?>

<?php if (($_products) && $_products->getSize()): ?>
    <?php
    /**
     * prepare for show label product
     */
    $shouldShowLabel = Mage::getStoreConfig('sm_productlabel/sm_productlabel/enable');
    $labelImageAllProducts = array();
    if ($shouldShowLabel) {
        $productLabelUrl = Mage::getBaseUrl('media') . 'images/productlabel/';

        $productIdLabel = array();
        foreach ($_products->getItems() as $_product){
            $productIdLabel[] = array(
                'id' => $_product->getId(),
                'label' => $_product->getProductLabel()
            );
        }
        // get label image for all products
        if (! empty($productIdLabel)) {
            $labelImageAllProducts = Mage::Helper('productlabel/retrievelabel')->getLabel($productIdLabel);
        }
    } // end if shouldSHowLabel
    ?>

    <h2 class="subtitle"><?php echo $this->__('Bestseller Products') ?></h2>
    <?php $_columnCount = $this->getColumnCount(); ?>
<div class="swiper-container bestseller">
    <div class="swiper-wrapper">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>

        <div class="swiper-slide">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="product-image">
                    <?php $_imgSize = 100; ?>
                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    <!--show image label-->
                    <?php  if ($shouldShowLabel) : ?>
                        <?php $labelImage = $labelImageAllProducts[$_product->getId()]; ?>
                        <?php foreach ($labelImage as $image) : ?>
                            <img <?php echo "class='" . $image['class'] . "'"; ?>
                                src="<?php echo $productLabelUrl . $image['imagename'] ?>" alt="">
                        <?php endforeach; ?>
                    <?php endif; ?>
                </a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></h3>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product, true, '-new') ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
<!--            </li>-->
            <?php /*if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif*/ ?>
        <?php endforeach; ?>
        </div>
    </div>
<!--    </ul>-->
<?php endif; ?>
<?php
    $NumberProductIsFeatured = $_products->count();
    $FeaturedConfig = Mage::getStoreConfig('sm_bestseller/sm_bestseller_config');
    $SlidePerView = $FeaturedConfig['bestsellerquantity'];
    $AutoPlayTime = isset($FeaturedConfig['autoplay']) ? $FeaturedConfig['autoplay'] : 5000;
    $SpeedAnimation = isset($FeaturedConfig['speedanimate']) ? $FeaturedConfig['speedanimate'] : 300;
?>
<script>
    var featuredSlider = new Swiper('.bestseller',{
        slidesPerView: <?php echo $SlidePerView ?>,
        autoplay: <?php echo $AutoPlayTime ?>,
        speed: <?php echo $SpeedAnimation ?>,
        <?php
            if($NumberProductIsFeatured >= $SlidePerView){
                echo 'loop: true' . ',';
            }
        ?>
    });
</script>