<div class = 'megamenu-container'>
    <ul id="megamenu">
        <?php
        $megaItems = $this->getMegaItem();


        foreach ($megaItems as $item){
            switch($item['type']){
                case SM_Megamenu_Block_Megamenu::CATEGORY_LINK_TYPE:?>

<!--                    <li class='category-link' category_id= --><?php //echo $item['value'];?><!-- >-->
                        <?php echo $this->createCategoryLink($item['title'],$item['value']);?>
<!--                    </li>-->
                       <?php
                    break;
                case SM_Megamenu_Block_Megamenu::CUSTOM_LINK_TYPE:
        ?>
                    <li class='custom-link'>
                        <a href='<?php echo $item['value']; ?>'>
                             <?php echo $item['title'];?>
                        </a>
                    </li>
        <?php
                    break;
                case SM_Megamenu_Block_Megamenu::BLOCK_LINK_TYPE:
                    ?>

                    <li class="block-link">
                        <?php echo $item['title'];?>
                        <ul>
<!--                            <li>-->
                                <?php echo $this->createBlockLink($item['value']); ?>
<!--                            </li>-->
                        </ul>
                    </li>
        <?php

                    break;
            }
        } // end foreach
        ?>
    </ul>

    <?php
    /**
     * Auto hightlight active (current) category
     */
    $pathIds = Mage::getModel('catalog/layer')->getCurrentCategory()->getPathIds();
    ?>
    <script>
        $j(function(){

            <?php foreach ($pathIds as $id) : ?>
            $j('li[category-id=<?php echo $id; ?>]').addClass('active-category');
            <?php endforeach; ?>
            /**
             * for Home
             */
            <?php $handleArray = Mage::app()->getLayout()->getUpdate()->getHandles();
                if(in_array('cms_index_index',$handleArray)){
                ?>
            $j('#megamenu >li:first-child').addClass('active-category');
            <?php
            }
         ?>
        });
    </script>
</div>




