<div class = 'megamenu-container'>
    <ul id="megamenu">
        <?php
        $megaItems = $this->getMegaItem();
        foreach ($megaItems as $item){
            switch($item['type']){
                case 1:
                    echo "<li class='category-link' category_id=".$item['value']. ">";
                    echo $this->createCategoryLink($item['title'],$item['value']);
                    echo "</li>";
                    break;

                case 2:
                    echo "<li class='custom-link'>";
                    echo $this->createCustomLink($item['title'],$item['value']);
                    echo "</li>";
                    break;
                case 3:
                    echo "<li class='block-link'>";
                    echo $this->createBlockLink($item['title'],$item['value']);
                    echo "</li>";
                    break;
            }
        } // end foreach
        ?>
    </ul>

    <?php
    /**
     * Auto hightlight active (current) category
     */
    $pathIds = Mage::getModel('catalog/layer')->getCurrentCategory()->getPathIds();
    ?>
    <script>
        $j(function(){

            <?php foreach ($pathIds as $id) : ?>
            $j('li[category_id=<?php echo $id; ?>]').addClass('active-category');
            <?php endforeach; ?>
            /**
             * for Home
             */
            <?php $handleArray = Mage::app()->getLayout()->getUpdate()->getHandles();
                if(in_array('cms_index_index',$handleArray)){
                ?>
            $j('#megamenu >li:first-child').addClass('active-category');
            <?php
            }
         ?>
        });
    </script>
</div>




