
<?php
    $filterFrontendRendererType =  $this->getAttributeModel()->getFilterFrontendRendererType();
?>
<?php //echo '<br/>' . $filterFrontendRendererType;?>
<?php if ($filterFrontendRendererType == SM_Filter_Model_Source_FilterRendererType::SELECT_TYPE) : ?>
        <select name="filter-select" onchange="window.location = $j(this).val()"/>
            <option value=""/><span>&ltPlease select&gt</span>
            <?php foreach ($this->getItems() as $_item): ?>
                <?php if ($_item->getCount() > 0): ?>

                    <option value="<?php echo $this->urlEscape($_item->getUrl()) ?>"/>
                    <?php echo $_item->getLabel(); ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach;?>
        </select>
<?php else : ?>
        <ol>
            <?php foreach ($this->getItems() as $_item): ?>
<!--                        --><?php //Zend_debug::dump( $_item->isSelected()); ?>
                <li <?php echo ($_item->isSelected() ? 'class="' . 'filter-hidden"' : '') ?>>
                    <?php if ($filterFrontendRendererType == SM_Filter_Model_Source_FilterRendererType::DEFAULT_TYPE
                            || $filterFrontendRendererType == SM_Filter_Model_Source_FilterRendererType::LINK_TYPE
                          ) : ?>

                        <?php if ($_item->getCount() > 0): ?>
                            <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                                <?php echo $_item->getLabel() ?>
                                <?php if ($this->shouldDisplayProductCount()): ?>
                                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                                <?php endif; ?>
                            </a>
                        <?php else: ?>
                            <span>
                                <?php echo $_item->getLabel(); ?>
                                <?php if ($this->shouldDisplayProductCount()): ?>
                                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                                <?php endif; ?>
                            </span>
                        <?php endif; ?>
                    <?php elseif ($filterFrontendRendererType == SM_Filter_Model_Source_FilterRendererType::CHECKBOX_TYPE) : ?>

                        <?php if ($_item->getCount() > 0): ?>
                            <input type='checkbox' name = 'filter-checkbox[]' <?php echo ($_item->isSelected()) ? 'checked=true': ''?>
                                   onclick="window.location = $j(this).val()"
                                   value="<?php echo $this->urlEscape($_item->getUrl()) ?>"/>
                            <?php echo $_item->getLabel() ?>
                            <?php if ($this->shouldDisplayProductCount()): ?>
                                <span class="count">(<?php echo $_item->getCount() ?>)</span>
                            <?php endif; ?>
                        <?php else: ?>
                            <span>
                                <?php echo $_item->getLabel(); ?>
                                <?php if ($this->shouldDisplayProductCount()): ?>
                                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                                <?php endif; ?>
                            </span>
                        <?php endif; ?>
                    <?php elseif ($filterFrontendRendererType == SM_Filter_Model_Source_FilterRendererType::COLOR_TYPE) : ?>
                        <?php if ($_item->getCount() > 0): ?>

                            <a class='color' href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                                <div class="filter-color"
                                     style="background-color: <?php echo $_item->getLabel() ?>;">

                                </div>
                                <span class="color-name"><?php echo $_item->getLabel(); ?></span>
                                <?php if ($this->shouldDisplayProductCount()): ?>
                                    <span class="count count-color">(<?php echo $_item->getCount() ?>)</span>
                                <?php endif; ?>
                            </a>
                        <?php else: ?>
                            <div class="filter-color" style="background-color: <?php echo $_item->getLabel() ?>;">
                                <?php if ($this->shouldDisplayProductCount()): ?>
                                    <span class="count">(<?php echo $_item->getCount() ?>)</span>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
            <?php endforeach;?>
        </ol>
<?php endif;?>
