<style>
    /* Demo Styles */
    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 13px;
        line-height: 1.5;
    }
    .swiper-container, .swiper-slide {
        width: 100%;
        height: 400px;
    }
    p.image-description{
        position: relative;
        bottom: 15%;
        background-color: rgba(0,255,0,0.8);
        color: black;
        text-shadow: #808080;
    }
    .swiper-container {
        /*width: 660px;*/
        width: 100%;
        background: #000;
        /*height: 250px;*/
        height: 400px;
        color: #fff;
        text-align: center;
    }
    .swiper-slide {
        /*height: 100%;*/
        opacity: 0.3;
        -webkit-transition: 300ms;
        -moz-transition: 300ms;
        -ms-transition: 300ms;
        -o-transition: 300ms;
        transition: 300ms;
    }
    .swiper-slide-active {
        opacity: 1;
    }


    .swiper-slide .title {
        font-style: italic;
        font-size: 42px;
        margin-top: 80px;
        margin-bottom: 0;
        line-height: 45px;
    }
    .pagination {
        position: absolute;
        z-index: 20;
        left: 10px;
        bottom: 10px;
    }
    .swiper-pagination-switch {
        display: inline-block;
        width: 8px;
        height: 8px;
        border-radius: 8px;
        background: #222;
        margin-right: 8px;
        opacity: 0.8;
        border: 1px solid #fff;
        cursor: pointer;
    }
    .swiper-visible-switch {
        background: #aaa;
    }
    .swiper-active-switch {
        background: #fff;
    }
    .swiper-slide img{
        height: 400px;
    }
</style>
<?php $ImageArray = $this->getSliderInfo(); ?>
<div class="swiper-container">
    <div class="swiper-wrapper">
        <?php foreach($ImageArray as $Image) : ?>
            <div class="swiper-slide" style="width: 600px;">
                <?php //$path =  Mage::getBaseUrl('media') . DS . 'images' . DS . 'slider' . DS . $Image['imagename'];?>
                <?php $path =  Mage::getBaseUrl('media') . "images/slider/" .  $Image['imagename'];?>
                <img src="<?php echo $path ?>" width="600px" alt="">
                <p class="image-description"><?php echo $Image['description']; ?></p>
            </div>
        <?php endforeach; ?>


    </div>
    <div class="pagination"></div>
</div>
<?php
    // get store config for slider
    $AllSliderConfig = Mage::getStoreConfig('sm_slider/sm_slider');
    $AutoPlayTime = isset($AllSliderConfig['autoplay']) ? $AllSliderConfig['autoplay'] : 5000;
    $SpeedAnimation = isset($AllSliderConfig['speedanimate']) ? $AllSliderConfig['speedanimate'] : 300;
    $Mode = isset($AllSliderConfig['mode']) ? $AllSliderConfig['mode'] : 'horizontal';
    $SlidePerView = isset($AllSliderConfig['slideperview']) ? $AllSliderConfig['slideperview'] : 1;

    $AdvanceSliderConfig = Mage::getStoreConfig('sm_slider/sm_slider_advance');
    $ExtraOption = isset($AdvanceSliderConfig['extraoption']) ? $AdvanceSliderConfig['extraoption'] : '';
?>
<script>
    window.onload = function() {
        var mySwiper = new Swiper('.swiper-container',{
            //Your options here:
            paginationClickable: true,
            centeredSlides: true,
<!--            mode: --><?php //if(isset($Mode)) echo "'" . $Mode . "'"; ?><!--,-->
            loop: true,
            pagination: '.pagination',

<!--            slidesPerView: --><?php //if(isset($SlidePerView)) echo $SlidePerView; ?><!--,-->
            slidesPerView: 'auto',
            speed: <?php if(isset($SpeedAnimation)) echo $SpeedAnimation; ?>,
            autoplay: <?php if(isset($AutoPlayTime)) echo $AutoPlayTime; ?>,

            <?php  echo $ExtraOption; ?>
            //etc..
        });
    }
//    window.onload = function() {
//        var mySwiper = new Swiper('.swiper-container',{
//            pagination: '.pagination',
//            paginationClickable: true,
//            centeredSlides: true,
//            loop: true,
//            autoplay: 3000,
//            slidesPerView: 'auto'
//        })
//    }
</script>