
<style>
     /*.swiper-slide img{*/
        /*height: 400px;*/
    /*}*/
    .pagination {
        position: absolute;
        z-index: 20;
        left: 10px;
        bottom: 10px;
    }

    .swiper-container, .swiper-slide {
        width: 100%;
        height: 400px;
    }
    p.image-description{
        position: relative;
        bottom: 15%;
        background-color: rgba(0,255,0,0.8);
        color: black;
        text-shadow: #808080;
    }
</style>


<?php $ImageArray = $this->getImagesForSlider();
    if($ImageArray == NULL){
        return FALSE;
    }
?>

<div class="swiper-container slider">
    <div class="swiper-wrapper">
        <?php foreach($ImageArray as $Image) : ?>
        <div class="swiper-slide">
            <?php //$path =  Mage::getBaseUrl('media') . DS . 'images' . DS . 'slider' . DS . $Image['imagename'];?>
            <?php $path =  Mage::getBaseUrl('media') . "images/slider/" .  $Image['imagename'];?>
            <img src="<?php echo $path ?>" alt="">
            <p class="image-description"><?php echo $Image['description']; ?></p>
        </div>
        <?php endforeach; ?>

    </div>
    <div class="pagination"></div>
</div>

<?php
// get store config for slider
$AllSliderConfig = Mage::getStoreConfig('sm_slider/sm_slider');
$AutoPlayTime = isset($AllSliderConfig['autoplay']) ? $AllSliderConfig['autoplay'] : 5000;
$SpeedAnimation = isset($AllSliderConfig['speedanimate']) ? $AllSliderConfig['speedanimate'] : 300;
$Mode = isset($AllSliderConfig['mode']) ? $AllSliderConfig['mode'] : 'horizontal';
$SlidePerView = isset($AllSliderConfig['slideperview']) ? $AllSliderConfig['slideperview'] : 1;

$AdvanceSliderConfig = Mage::getStoreConfig('sm_slider/sm_slider_advance');
$ExtraOption = isset($AdvanceSliderConfig['extraoption']) ? $AdvanceSliderConfig['extraoption'] : '';

?>
<script>
    var sliderswipe = new Swiper('.slider',{
        mode: <?php if(isset($Mode)) echo "'" . $Mode . "'"; ?>,
        loop: true,
        pagination: '.pagination',
        paginationClickable: true,
        slidesPerView: <?php if(isset($SlidePerView)) echo $SlidePerView; ?>,
        speed: <?php if(isset($SpeedAnimation)) echo $SpeedAnimation; ?>,
        autoplay: <?php if(isset($AutoPlayTime)) echo $AutoPlayTime; ?>,
        <?php  echo $ExtraOption; ?>
    });
</script>