<?php
/**
 * This template show Slider on Home Page of site
 */
?>

<?php $imageArray = $this->getImagesForSlider(); // get all Image infomation for slider?>

<?php if(! empty($imageArray)) : ?>
<!--    <div class="swiper-container slider">-->
    <div class="swiper-container slider <?php echo $this->getSliderClass(); ?>">
        <div class="swiper-wrapper">
            <?php foreach($imageArray as $image) : ?>
                <div class="swiper-slide">
                    <?php $path =  Mage::getBaseUrl('media') . "images/slider/" .  $image['imagename'];?>
                    <img src="<?php echo $path ?>" alt="">
                    <p class="image-description"><?php echo $image['description']; ?></p>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="pagination"></div>
    </div>
    <?php
    // get store config for slider

    $sliderType = Mage::getStoreConfig('sm_slider/sm_slider/type');

    $allSliderConfig = Mage::getStoreConfig('sm_slider/sm_slider');
    $autoPlayTime    = isset($allSliderConfig['autoplay']) ? $allSliderConfig['autoplay'] : 5000;
    $speedAnimation  = isset($allSliderConfig['speedanimate']) ? $allSliderConfig['speedanimate'] : 300;
    $mode            = isset($allSliderConfig['mode']) ? $allSliderConfig['mode'] : 'horizontal';
    $slidePerView    =  1;

    if ($sliderType == 'activecenter'){
        $slidePerView = isset($allSliderConfig['slideperview']) ? $allSliderConfig['slideperview'] : 3;
    }

//    $config = $this->getSliderConfig();
//    Zend_debug::dump($config);
//    foreach ($config as $key => $value) {
//        echo $key . ':' . $value . ',';
//    }
//    die();

    ?>
    <script>
        $j(function(){
            var containerWidth = $j('.slider.swiper-container').width();
            var containerHeight = $j('.slider.swiper-container').height();
//            alert(containerWidth);
            $j('.slider .swiper-slide img').each(function(){
                $j(this).width(containerWidth / <?php echo $slidePerView; ?>)
                        .height(containerHeight)
                ;
            })
        });

        var sliderswipe = new Swiper(".<?php echo $this->getSliderClass(); ?>",{
            mode: <?php  echo "'" . $mode . "'"; ?>,
<!--            --><?php
//                $config = $this->getSliderConfig();
//                Zend_debug::dump($config);
//                foreach ($config as $key => $value) {
//                    echo $key . ':' . $value . ',';
//                }
//
//            ?>
            loop: true,
            pagination: '.pagination',
            paginationClickable: true,
            <?php if ($sliderType == 'activecenter'){
                echo 'slidesPerView:' . $slidePerView . ',';
            }
            ?>
            speed: <?php  echo $speedAnimation; ?>,
            autoplay:  <?php echo $autoPlayTime; ?>,
            centeredSlides: true
        });
    </script>
<?php endif; ?>
